### ISSUE TITLE
Some questions about this code.

### ISSUE THREAD

**Issue by ztf-ucas** [tankche1/Image-Deformation-Meta-Networks-for-One-Shot-Learning#1]
Thank you very much for providing this code. Great job! But I have some questions:
- **What is the meaning of chooseNum in args?**
In  onlyBasetwoLoss.py line 407:
`choose = np.random.randint(0,args.chooseNum)`

**Awaiting for your reply! Thank you very much.**

**Comment by tankche1** [comment]
I want to randomly select from the K nearest neighbor. chooseNum is K.
